export const avatarOptions = {
  faces: [
    "◉‿◉",
    "˘◡˘",
    "◕‿◕",
    "ʘ‿ʘ",
    "⊙‿⊙",
    "≧◡≦",
    "◠‿◠",
    "◕ω◕",
  ],
  eyes: [
    "• •",
    "◕ ◕",
    "○ ○",
    "⊙ ⊙",
    "⚆ ⚆",
    "✧ ✧",
    "♥ ♥",
    "◉ ◉",
  ],
  mouths: [
    "‿",
    "◡",
    "▽",
    "ω",
    "⌣",
    "◠",
    "◞",
    "◟",
  ],
  accessories: [
    "none",
    "🎩",
    "👓",
    "🎀",
    "🌟",
    "✨",
    "⭐",
    "💫",
  ],
  colorThemes: [
    { name: "Classic", bg: "bg-indigo-500", text: "text-white" },
    { name: "Ocean", bg: "bg-blue-500", text: "text-white" },
    { name: "Forest", bg: "bg-emerald-500", text: "text-white" },
    { name: "Sunset", bg: "bg-orange-500", text: "text-white" },
    { name: "Royal", bg: "bg-purple-500", text: "text-white" },
    { name: "Rose", bg: "bg-pink-500", text: "text-white" },
    { name: "Gold", bg: "bg-yellow-500", text: "text-black" },
    { name: "Midnight", bg: "bg-gray-800", text: "text-white" },
  ],
}; 